// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © DamiSneeze

//@version=6
indicator("The Method", overlay = true, calc_bars_count = 0, max_boxes_count = 500, max_lines_count = 500)
// import TradingView/ta/12
// ^ where did this come from?

// SETTINGS
// All customizability and inputs that this indicator will use

//Group - Higher Time Frame (HTF)
string htf1 = input.timeframe("", "HTF 1", group="HTF", inline="htf_set1", display=display.none)
bool display_htf1 = input.bool(true, "", group="HTF", inline="htf_set1")
string htf2 = input.timeframe("", "HTF 2", group="HTF", inline="htf_set1",  display=display.none,
tooltip="First and second higher timeframe to detect zones of liquidity on. Can toggle each timeframe on or off individually.")
bool display_htf2 = input.bool(true, "", group="HTF", inline="htf_set1")
string htf3 = input.timeframe("", "HTF 3", group="HTF", inline="htf_set2", display=display.none)
bool display_htf3 = input.bool(true, "", group="HTF", inline="htf_set2")
string htf4 = input.timeframe("", "HTF 4", group="HTF", inline="htf_set2",  display=display.none,
tooltip="Third and fourth higher timeframe to detect zones of liquidity on. Can toggle each timeframe on or off individually.")
bool display_htf4 = input.bool(true, "", group="HTF", inline="htf_set2")

//Group - Fair Value Gap (FVG)
bool display_fvgs = input.bool(true, "Display FVGs", group="FVG", tooltip="Master toggle for turning on or off the display of Fair Value Gaps.")
float fvg_min_size = input.float(0.15, "Minimum FVG Size", minval=0, group='FVG', display=display.none,
tooltip="Determines the minimum size that a FVG can be. Can be used to prevent very small FVGs that are indistinguisable from a line.")
float fvg_max_size = input.float(2, "Maximum FVG Size", minval=0, group='FVG', display=display.none,
tooltip="Determines the maximum size that a FVG can be. Can be used to prevent very large FVGs that span the chart.")
bool fvg_multiTF = input.bool(true, "FVG Multi TimeFrame Display Toggle", group='FVG',
tooltip="Determines if Fair Value Gaps are pulled from multiple timeframes and displayed in an overlay.")

//Group - Order Block (OB)
bool display_OBs = input.bool(true, "Display OBs", group="OB", tooltip="Master toggle for turning on or off the display of Fair Value Gaps.")
string ob_size = input.string("Full", "OB Size", ["Small", "Medium", "Full"], "Used to adjust the size and calcuation of an Order Block.", group="OB", display=display.none)


// TYPES
// All types and enums used to store/display information


//@enum An enumeration of the bullish or bearish sentiment of a liquidity zone. (FVGs, Liquidity Pools, etc.)
//@field BULL  Specifies a liquidity zone where buyers are likely to make a move.
//@field BEAR  Specifies a liquidity zone where sellers are likely to make a move.
enum sentiment
    BULL
    BEAR

//@enum An enumeration of the status of zones of liquidity that price can react off of. (FVGs, Liquidity Pools, etc.)
//@field OPEN   Specifies a zone that price has not disrespected.
//@field MITIGATED   Specifies a zone that price has gone more than 50% through.
//@field CLOSED  Specifies a zone that price has closed beyond.
enum status
    OPEN
    MITIGATED
    CLOSED

//@type A custom object that holds information on a Fair Value Gap.
//@field id A unique identifier to avoid plotting the same FVG multiple times.
//@field top  Stores the top price of the FVG. The point price must close beyond to invalidate a bearish FVG.
//@field bottom  Stores the bottom price of the FVG. The point price must close beyond to invalidate a bullish FVG.
//@field middle  Stores the middle price of the FVG.
//@field start  Stores the chart time that a FVG starts from.
//@field direction  Stores an enumeration value for the sentiment of bullish or bearish.
//@field state  Stores an enumeration value for whether the FVG is open, mitigated, or closed.
//@field display  Stores the box object that is displayed on the chart.
//@field midline  Stores the line object that displays the middle of the FVG.
//@field bounce_line  Stores a line object representing where price must close beyond in order to invalidate a FVG. Only appears when fvg.state == status.MITIGATED. 
type fvg
    string id
    float top
    float bottom
    float middle
    int start
    sentiment direction
    status state
    box display
    line midline
    line bounce_line

//@type A custom object that holds information on an Order Block.
//@field top  Stores the top price of the OB. The point price must close beyond to invalidate a bearish OB.
//@field bottom  Stores the bottom price of the OB. The point price must close beyond to invalidate a bullish OB.
//@field start  Stores the chart time that an OB starts from.
//@field direction  Stores an enumeration value for the sentiment of bullish or bearish.
//@field state  Stores an enumeration value for whether the OB is open, mitigated, or closed.
//@field mitigation_count  Stores the number of candles that have interacted with an OB. OB will be invalidated after a specified amount. This variable resets to 0 after price moves away from an OB.
//@field display  Stores the box object that is displayed on the chart.
type ob
    string id
    chart.point top
    chart.point bottom
    sentiment direction
    status state
    int mitigation_count
    box display


//FUNCTIONS
// Reusable code that will be repeatedly called on


incorrect_tf(string tf1, string tf2, string tf3, string tf4, bool bool1, bool bool2, bool bool3, bool bool4) =>
    int current = timeframe.in_seconds()
    if (timeframe.in_seconds(tf1) < current) and bool1
        "true"
    else if (timeframe.in_seconds(tf2) < current) and bool2
        "true"
    else if (timeframe.in_seconds(tf3) < current) and bool3
        "true"
    else if (timeframe.in_seconds(tf4) < current) and bool4
        "true"

duplicate_tf(string htf, array<string> arr) =>
    for tf in arr
        if htf == tf or na(htf)
            "true"

//@function Takes an descending order array of specified indexes that 
// are no longer useful and a target liquidity zone UDT array; and removes
// the specified indexes. Descending order makes it so a removal will not
// change the index of subsequent removals.
garbage_collect(array<int> idxs, arr) =>
    for idx in idxs
        array.remove(arr, idx)

//@function This function checks the last bar (low[1]/high[1]) and
// the bar from three candles ago (low[3]/high[3]); creating
// a FVG object after it identifies whether a gap exists
// between them.
detect_fvg() =>
    fvg FVG = na
    if high[3] < low[1] and (low[1] - high[3] > fvg_min_size) and (low[1] - high[3] < fvg_max_size)
        int start = time - (timeframe.in_seconds() * 1000 * 2)
        float top = low[1]
        float bottom = high[3]
        float middle = math.avg(top, bottom)
        string id = str.format("{0}-{1}", top, bottom)

        FVG := fvg.new(id, top, bottom, middle, start, sentiment.BULL, status.OPEN)

    else if low[3] > high[1] and (low[3] - high[1] > fvg_min_size) and (low[1] - high[3] < fvg_max_size)
        int start = time - (timeframe.in_seconds() * 1000 * 2)
        float top = low[3]
        float bottom = high[1]
        float middle = math.avg(top, bottom)
        string id = str.format("{0}-{1}", top, bottom)

        FVG := fvg.new(id, top, bottom, middle, start, sentiment.BEAR, status.OPEN)

    FVG

plot_fvg(fvg FVG, array<fvg> bull_arr, array<fvg> bear_arr) => 
    int start = FVG.start
    chart.point top = chart.point.from_time(start, FVG.top)
    chart.point bottom = chart.point.from_time(start, FVG.bottom)
    chart.point midpoint1 = chart.point.from_time(start, FVG.middle)
    chart.point midpoint2 = chart.point.from_time(timenow, FVG.middle)
    // timenow because of weird bug that makes the line horizontal
    // regardless of the x1 and x2 being different
    if FVG.direction == sentiment.BULL and (bull_arr.size() == 0 or (bull_arr.size() != 0 and FVG.id != bull_arr.get(0).id))
        FVG.display := box.new(top, bottom, border_width=0, bgcolor=color.new(color.blue, 85), extend=extend.right, xloc=xloc.bar_time)
        FVG.midline := line.new(midpoint1, midpoint2, xloc.bar_time, color=color.blue, extend=extend.right)
        bull_arr.unshift(FVG)

    else if FVG.direction == sentiment.BEAR and (bear_arr.size() == 0 or (bear_arr.size() != 0 and FVG.id != bear_arr.get(0).id))
        FVG.display := box.new(top, bottom, border_width=0, bgcolor=color.new(color.orange, 85), extend=extend.right, xloc=xloc.bar_time)
        FVG.midline := line.new(midpoint1, midpoint2, xloc.bar_time, color=color.orange, extend=extend.right)
        bear_arr.unshift(FVG)

update_bullish_fvgs(array<fvg> bull_arr, float htf_close = na, float htf_low = low) =>
    array<int> closed_idxs = array.new<int>()
    for [idx, FVG] in bull_arr
        if not na(htf_close) and htf_close < FVG.bottom
            box.delete(FVG.display)
            line.delete(FVG.midline)
            if not na(FVG.bounce_line)
                line.delete(FVG.bounce_line)
            array.unshift(closed_idxs, idx)
            continue
        if htf_low < FVG.middle and FVG.state != status.MITIGATED
            box bx = FVG.display
            line ln = FVG.midline
            box.set_right(bx, time)
            // box.set_extend(bx, extend.none)
            box.set_bgcolor(bx, color.new(color.silver, 50))
            line.set_x2(ln, time + 1)
            // line.set_extend(ln, extend.none)
            line.set_color(ln, color.black)
            chart.point bouncepoint1 = chart.point.from_time(FVG.start, FVG.bottom)
            chart.point bouncepoint2 = chart.point.from_time(timenow, FVG.bottom)
            FVG.bounce_line := line.new(bouncepoint1, bouncepoint2, xloc.bar_time, extend=extend.right, color=color.new(color.blue, 50), width=3)
            FVG.state := status.MITIGATED
            continue
        if htf_low > FVG.middle
            break

    garbage_collect(closed_idxs, bull_arr)

update_bearish_fvgs(array<fvg> bear_arr, float htf_close = na, float htf_high = high) =>
    array<int> closed_idxs = array.new<int>()
    for [idx, FVG] in bear_arr
        if not na(htf_close) and htf_close > FVG.top
            box.delete(FVG.display)
            line.delete(FVG.midline)
            if not na(FVG.bounce_line)
                line.delete(FVG.bounce_line)
            array.unshift(closed_idxs, idx)
            continue
        if htf_high > FVG.middle and FVG.state != status.MITIGATED
            box bx = FVG.display
            line ln = FVG.midline
            box.set_right(bx, time)
            // box.set_extend(bx, extend.none)
            box.set_bgcolor(bx, color.new(color.silver, 50))
            line.set_x2(ln, time + 1)
            // line.set_extend(ln, extend.none)
            line.set_color(ln, color.black)
            chart.point bouncepoint1 = chart.point.from_time(FVG.start, FVG.top)
            chart.point bouncepoint2 = chart.point.from_time(timenow, FVG.top)
            FVG.bounce_line := line.new(bouncepoint1, bouncepoint2, xloc.bar_time, extend=extend.right, color=color.new(color.orange, 50), width=3)
            FVG.state := status.MITIGATED
            continue
        if htf_high < FVG.middle
            break
    
    garbage_collect(closed_idxs, bear_arr)

detect_ob() =>
    ob OB = na
    
    float trigger = ta.change(ta.rsi(close[1], 14), 1)
    float bull_pivot = ta.lowest(low[1], 2)
    float bear_pivot = ta.highest(high[1], 2)

    if bull_pivot - ta.lowest(low[1], 7) < 0.15 and trigger > 5.5
        chart.point y = chart.point.from_time(time - timeframe.in_seconds() * 1000, bull_pivot)
        chart.point x = na
        if ob_size == "Full"
            x := low[1] < low[2] ? chart.point.from_time(time - timeframe.in_seconds() * 1000, hl2[1]) : chart.point.from_time(time - timeframe.in_seconds() * 2000 , hl2[2])
        else if ob_size == "Medium"
            x := low[1] < low[2] ? chart.point.from_time(time - timeframe.in_seconds() * 1000, ((2 * low[1]) + high[1]) / 3) : chart.point.from_time(time - timeframe.in_seconds() * 2000, ((2 * low[2]) + high[2]) / 3)
        else
            x := low[1] < low[2] ? chart.point.from_time(time - timeframe.in_seconds() * 1000, (hl2[1] + low[1]) / 2) : chart.point.from_time(time - timeframe.in_seconds() * 2000, (hl2[2] + low[2]) / 2)
        
        string id = str.format("{0}-{1}", x.price, y.price)
        OB := ob.new(id, x, y, sentiment.BULL, status.OPEN, 0)

    if bear_pivot - ta.highest(high[1], 7) > -0.15 and trigger < -5.5
        chart.point x = chart.point.from_time(time - timeframe.in_seconds() * 1000, bear_pivot)
        chart.point y = na

        if ob_size == "Full"
            y := high[1] > high[2] ? chart.point.from_time(time - timeframe.in_seconds() * 1000, hl2[1]) : chart.point.from_time(time - timeframe.in_seconds() * 2000, hl2[2])
        else if ob_size == "Medium"
            y := high[1] > high[2] ? chart.point.from_time(time - timeframe.in_seconds() * 1000, ((2 * high[1]) + low[1]) / 3) : chart.point.from_time(time - timeframe.in_seconds() * 2000, ((2 * high[2]) + low[2]) / 3)
        else
            y := high[1] > high[2] ? chart.point.from_time(time - timeframe.in_seconds() * 1000, (hl2[1] + high[1]) / 2) : chart.point.from_time(time - timeframe.in_seconds() * 2000, (hl2[2] + high[2]) / 2)
        
        string id = str.format("{0}-{1}", x.price, y.price)
        OB := ob.new(id, x, y, sentiment.BEAR, status.OPEN, 0)
    
    OB

plot_ob(ob OB, array<ob> bull_arr, array<ob> bear_arr) =>
    if OB.direction == sentiment.BULL  and (bull_arr.size() == 0 or (bull_arr.size() != 0 and OB.id != bull_arr.get(0).id))
        OB.display := box.new(OB.top, OB.bottom, extend=extend.right, bgcolor=color.new(color.lime, 80), xloc = xloc.bar_time)
        bull_arr.unshift(OB)
    else if OB.direction == sentiment.BEAR  and (bear_arr.size() == 0 or (bear_arr.size() != 0 and OB.id != bear_arr.get(0).id))
        OB.display := box.new(OB.top, OB.bottom, extend=extend.right, bgcolor=color.new(color.red, 80), xloc = xloc.bar_time)
        bear_arr.unshift(OB)
    
update_bullish_obs(array<ob> bull_arr, float htf_close = close, float htf_low = low) =>
    array<int> closed_idxs = array.new<int>()
    for [idx, OB] in bull_arr
        float top = OB.top.price
        float bottom = OB.bottom.price
        if htf_close[1] < bottom
            box.delete(OB.display)
            array.unshift(closed_idxs, idx)
            continue
        if htf_close > top and OB.state != status.MITIGATED
            break
        if htf_close > top and OB.state == status.MITIGATED
            OB.state := status.OPEN
            box bx = OB.display
            bx.set_bgcolor(color.new(color.lime, 80))
            bx.set_border_width(0)
            continue
        if htf_low < top and OB.state == status.OPEN
            OB.state := status.MITIGATED
            box bx = OB.display
            bx.set_bgcolor(color.new(color.silver, 80))
            bx.set_border_width(5)
        
    garbage_collect(closed_idxs, bull_arr)

update_bearish_obs(array<ob> bear_arr, float htf_close = close, float htf_high = high) =>
    array<int> closed_idxs = array.new<int>()
    for [idx, OB] in bear_arr
        float top = OB.top.price
        float bottom = OB.bottom.price
        if htf_close[1] > top
            box.delete(OB.display)
            array.unshift(closed_idxs, idx)
            continue
        if htf_close < bottom and OB.state != status.MITIGATED
            break
        if htf_close < bottom and OB.state == status.MITIGATED
            OB.state := status.OPEN
            box bx = OB.display
            bx.set_bgcolor(color.new(color.red, 80))
            bx.set_border_width(0)
            continue
        if htf_high > bottom and OB.state == status.OPEN
            OB.state := status.MITIGATED
            box bx = OB.display
            bx.set_bgcolor(color.new(color.silver, 80))
            bx.set_border_width(5)
        
    garbage_collect(closed_idxs, bear_arr)



// RUNTIME
// Line of logic that is run for every bar execution


// Fair Value Gaps
if display_fvgs
    if fvg_multiTF
        if not na(incorrect_tf(htf1, htf2, htf3, htf4, display_htf1, display_htf2, display_htf3, display_htf4))
            runtime.error("""While FVG Multi Timeframe Display Toggle is enabled in settings, the timeframe of the chart must not be greater than any 
            higher timeframes chosen.""")

        array<string> selected_tfs = array.new<string>()
        
        if display_htf1 and na(duplicate_tf(htf1, selected_tfs))
            selected_tfs.unshift(htf1)
            var array<fvg> bull_fvgs_1 = array.new<fvg>()
            var array<fvg> bear_fvgs_1 = array.new<fvg>()
            [FVG, htf_close, htf_high, htf_low] = request.security(syminfo.tickerid, htf1, [detect_fvg(), close[1], high, low])
            if not na(FVG)
                plot_fvg(FVG, bull_fvgs_1, bear_fvgs_1)

            if bull_fvgs_1.size() > 0
                update_bullish_fvgs(bull_fvgs_1, htf_close, htf_low)

            if bear_fvgs_1.size() > 0
                update_bearish_fvgs(bear_fvgs_1, htf_close, htf_high)
            
        if display_htf2 and na(duplicate_tf(htf2, selected_tfs))
            selected_tfs.unshift(htf2)
            var array<fvg> bull_fvgs_2 = array.new<fvg>()
            var array<fvg> bear_fvgs_2 = array.new<fvg>()

            [FVG, htf_close, htf_high, htf_low] = request.security(syminfo.tickerid, htf2, [detect_fvg(), close[1], high, low])
            if not na(FVG)
                plot_fvg(FVG, bull_fvgs_2, bear_fvgs_2)

            if bull_fvgs_2.size() > 0
                update_bullish_fvgs(bull_fvgs_2, htf_close, htf_low)

            if bear_fvgs_2.size() > 0
                update_bearish_fvgs(bear_fvgs_2, htf_close, htf_high)

        if display_htf3 and na(duplicate_tf(htf3, selected_tfs))
            selected_tfs.unshift(htf3)
            var array<fvg> bull_fvgs_3 = array.new<fvg>()
            var array<fvg> bear_fvgs_3 = array.new<fvg>()

            [FVG, htf_close, htf_high, htf_low] = request.security(syminfo.tickerid, htf3, [detect_fvg(), close[1], high, low])
            if not na(FVG)
                plot_fvg(FVG, bull_fvgs_3, bear_fvgs_3)

            if bull_fvgs_3.size() > 0
                update_bullish_fvgs(bull_fvgs_3, htf_close, htf_low)

            if bear_fvgs_3.size() > 0
                update_bearish_fvgs(bear_fvgs_3, htf_close, htf_high)

        if display_htf4 and na(duplicate_tf(htf4, selected_tfs))
            selected_tfs.unshift(htf4)
            var array<fvg> bull_fvgs_4 = array.new<fvg>()
            var array<fvg> bear_fvgs_4 = array.new<fvg>()

            [FVG, htf_close, htf_high, htf_low] = request.security(syminfo.tickerid, htf4, [detect_fvg(), close[1], high, low])
            if not na(FVG)
                plot_fvg(FVG, bull_fvgs_4, bear_fvgs_4)

            if bull_fvgs_4.size() > 0
                update_bullish_fvgs(bull_fvgs_4, htf_close, htf_low)

            if bear_fvgs_4.size() > 0
                update_bearish_fvgs(bear_fvgs_4, htf_close, htf_high)

    else
        var array<fvg> bull_fvgs = array.new<fvg>()
        var array<fvg> bear_fvgs = array.new<fvg>()

        fvg FVG = detect_fvg()
        if not na(FVG)
            plot_fvg(FVG, bull_fvgs, bear_fvgs)

        if bull_fvgs.size() > 0
            update_bullish_fvgs(bull_fvgs, close[1])

        if bear_fvgs.size() > 0
            update_bearish_fvgs(bear_fvgs, close[1])


// Order Block
if display_OBs

    var array<ob> bull_obs = array.new<ob>()
    var array<ob> bear_obs = array.new<ob>()
    ob OB = detect_ob()
    if not na(OB)
        plot_ob(OB, bull_obs, bear_obs)
    if bull_obs.size() > 0
        update_bullish_obs(bull_obs, close, low)
    if bear_obs.size() > 0
        update_bearish_obs(bear_obs, close, high)

    

//current colors are placeholders; add settings for colors later as well
// Order blocks must be the lowest of x candles, create a gap, and
// lead to a break of structure

//add setting for fvgs to only be made from candle during market hours
// using 'time' variable makes FVGs from overnight get plotted a little off,
// don't know if there is a fix fr

// should i initialize the multiple arrays or fvg_arrays with a wrapper and
// loop through them instead of 4 conditional blocks
// with this i could target lower tf
// ^ do this after multi OBs ^ easier logic for skipping non selected htfs

//possible functionality to close htf fvg based on a different tf
// for example 1d bearish would be removed from 4hr candle closing above it

//i wish i could know what tf a fvg is from
